name: 'Reformat SQL Files'
description: 'Reformats SQL files'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
inputs:
  dialect:
    description: The dialect of SQL to format
    required: true
    default: "tsql"
runs:
  using: node20
  main: main.js
