#!/bin/sh -l
set -eu

curl http://architectshack.com/GetFile.aspx?Page=PoorMansTSqlFormatter\&File=SqlFormatter.1.6.10.zip --output sqlformatter.zip 
ls
unzip sqlformatter.zip *.exe -d sqlformatter
chmod +x sqlformatter/SqlFormatter.exe
find ./ -iname '*.sql' -type f -exec bash -c 'mono sqlformatter/SqlFormatter.exe "$0" /is:"    " /tc /sk /r /sac /mw:120 /b- /bjo /cb:1 /st:4 /eil- /ecs- /ecl /uk /sb:2 /ebc /ebe' {} \;
find ./ -iname '*.sql' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

