#!/bin/sh -l
set -eu

echo Reformatting files
find ./ -iname '*.sql' -type f -exec bash -c 'python "$0" /is:"    " /tc /sk /r /sac /mw:999999999 /b- /bjo /cb:1 /st:4 /eil- /ecs- /ecl /uk /sb:2 /ebc /ebe' {} \;

echo Converting tabs to spaces
find ./ -iname '*.sql' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

rm -fr sqlformatter
rm -fr sqlformatter.zip
