name: "Test: Workflow"

on:
  push:
    branches-ignore:
      - "release/*"
      - "hotfix/*"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}-test
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          token: ${{secrets.SOURCE_PUSH_TOKEN}}
      - name: Reformat
        uses: ./.github/..
      - if: |-
          ${{github.event.pull_request.draft == false
          && ( !startsWith(github.head_ref, 'release/')
          && !startsWith(github.head_ref, 'hotfix/') )
          && github.actor != 'dependabot[bot]'}}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "[Reformat] SQL Files to common format"
          file_pattern: "*.sql"
          commit_user_name: "fun-sqlfmt[bot]"
          commit_user_email: "credfeto@users.noreply.github.com"
          commit_author: "fun-sqlfmt[bot] <credfeto@users.noreply.github.com>"
          skip_dirty_check: false
